#!/bin/bash
 
#files=*
 
for file in .??*
do
  echo "${file}"
  filepath="${PWD}/${file}"
  homefile="${HOME}/${file}"
 
  # . と .. .git は抜かす
  test $file == ".git" && continue
  test $file == "." && continue
  test $file == ".." && continue
  test $file == "make_ln" && continue
  test $file == "README.md" && continue
  test $file == "Brewfile" && continue
 
  echo "${homefile}"
  # .hogehogeが存在しなければ、シンボリックリンクを作成
  if [ ! -e "${homefile}" ]; then
    echo "${file} not exists, make symbolic link to ${homefile}"
    ln -s "${filepath}" "${homefile}"
  else
    echo "${file} exists"
  fi
done
